name: Build And Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        id: mycache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.mycache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline
      - name: Cache Verify
        if: steps.mycache.outputs.cache-hit != 'false'
        run: npm cache add ~/.npm
      - name: Build
        run: npm run build --prod --sourceMap=false
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
